/**
 * Helpers for serving WebP companions alongside the JPG/PNG originals.
 *
 * The build pipeline (scripts/optimize-images.mjs) writes a `.webp` version
 * next to every JPG/PNG when the WebP is smaller. We use `<picture>` so
 * supporting browsers download only the WebP and the original is left as
 * a graceful fallback for the rest.
 *
 * Important: not every JPG/PNG has a WebP companion (the optimizer skips
 * cases where the WebP would be larger than the source — e.g. some flat
 * illustrations). If we still pointed `<picture>` `<source>` at a missing
 * `.webp`, the browser would commit to that source, get a 404, and render
 * a broken image (it does *not* automatically fall back to the inner
 * `<img>` on a network failure). The manifest generated by
 * `scripts/generate-webp-manifest.mjs` lists every `.webp` that actually
 * exists under `public/images/`, so we only advertise those.
 */
import { webpManifest } from './generatedWebpManifest';

const RAW_IMAGE_RE = /\.(jpe?g|png)(\?.*)?$/i;

export function webpSrcFor(src: string): string | null {
  if (!RAW_IMAGE_RE.test(src)) return null;
  const candidate = src.replace(RAW_IMAGE_RE, '.webp$2');
  const filename = filenameUnderImagesDir(candidate);
  if (!filename) return null;
  return webpManifest.has(filename) ? candidate : null;
}

const IMAGES_PREFIX_RE = /(?:^|\/)images\/([^/?#]+)(?:\?.*)?$/;

function filenameUnderImagesDir(src: string): string | null {
  const match = src.match(IMAGES_PREFIX_RE);
  if (!match) return null;
  try {
    return decodeURIComponent(match[1]);
  } catch {
    return match[1];
  }
}

/**
 * Encode a path that may live under `/images/<filename>` so spaces / Cyrillic
 * get URL-escaped while leading `/` stays untouched.
 */
export function encodePublicPath(path: string): string {
  if (!path.startsWith('/')) return encodeURI(path);
  return '/' + path.slice(1).split('/').map(encodeURIComponent).join('/');
}
